[notice]
id = "mydns******"
password = "***********"
cron = "@hourly"
//s m h dom mon dow
//https://godoc.org/github.com/robfig/cron

[log.slack]
enable = true
hookURL = "https://hooks.slack.com/services/*********/*********/************************"
