[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/comail/colog"

[[constraint]]
  name = "github.com/robfig/cron"
  version = "1.0.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/xmlpath.v2"

[prune]
  go-tests = true
  unused-packages = true
